sybinit.release_directory: /opt/sybase
sybinit.product: sqlsrv
sqlsrv.server_name: TESTSYBASE
sqlsrv.sa_password: sa_pass
sqlsrv.new_config: yes
sqlsrv.do_add_server: yes
sqlsrv.network_protocol_list: tcp
sqlsrv.network_hostname_list: localhost
sqlsrv.network_port_list: 5000
sqlsrv.application_type: MIXED
sqlsrv.server_page_size: 16k
sqlsrv.force_buildmaster: no
sqlsrv.addl_cmdline_parameters:
sqlsrv.master_device_physical_name: /var/sybase/TESTSYBASE/master.dat
sqlsrv.master_device_size: 3000
sqlsrv.master_database_size: 2000
sqlsrv.errorlog: /opt/sybase/ASE-16_0/install/MYSYBASE.log
sqlsrv.sort_order:	bin_utf8
sqlsrv.default_characterset:	utf8
sqlsrv.default_language:	us_english
sqlsrv.do_upgrade: no
sqlsrv.sybsystemprocs_device_physical_name: /var/sybase/TESTSYBASE/sysprocs.dat
sqlsrv.sybsystemprocs_device_size: 2000
sqlsrv.sybsystemprocs_database_size: 2000
sqlsrv.sybsystemdb_device_physical_name: /var/sybase/TESTSYBASE/sybsysdb.dat
sqlsrv.sybsystemdb_device_size: 500
sqlsrv.sybsystemdb_database_size: 500
sqlsrv.tempdb_device_physical_name: /var/sybase/TESTSYBASE/tempdbdev.dat
sqlsrv.tempdb_device_size: 500
sqlsrv.tempdb_database_size: 500
sqlsrv.default_backup_server: MYSYBASE_BS
sqlsrv.do_configure_pci: yes
sqlsrv.sybpcidb_device_physical_name: /var/sybase/TESTSYBASE/sybpcidbdev_data.dat
sqlsrv.sybpcidb_device_size: 2000
sqlsrv.sybpcidb_database_size: 2000
sqlsrv.do_optimize_config: no
sqlsrv.avail_physical_memory: 2048
sqlsrv.avail_cpu_num: 1
